services:
  db:
    image: postgres:15
    container_name: salonki-postgres

    environment:
      POSTGRES_USER: salonki
      POSTGRES_PASSWORD: salonki
      POSTGRES_DB: salonki

    ports:
      - "5432:5432"

    volumes:
      - salonki_postgres_data:/var/lib/postgresql/data

volumes:
  salonki_postgres_data: