import assert from 'node:assert/strict';
import { isLocale } from '../src/i18n/locales.ts';
import { switchLocalePath, publicRoutes } from '../src/i18n/routing.ts';
for (const locale of ['en', 'fi', 'sv']) assert(isLocale(locale));
for (const locale of ['de', 'EN', '', 'en-US', 'constructor']) assert(!isLocale(locale));
assert.equal(switchLocalePath('/en', 'fi'), '/fi');
assert.equal(switchLocalePath('/fi/events/salsa-social-september?view=list#details', 'sv'), '/sv/events/salsa-social-september?view=list#details');
assert.equal(switchLocalePath('/sv/meeting-room', 'en'), '/en/meeting-room');
assert.equal(switchLocalePath('/unsupported', 'fi'), '/fi');
assert.equal(publicRoutes.length, 7);
assert.deepEqual(publicRoutes.map(route => route.path), ['#home', '#food-coffee', '#bar', '#events', '#souvenirs', '#meeting-room', '#contact']);
assert.equal(switchLocalePath('/en?preview=1#meeting-room', 'sv'), '/sv?preview=1#meeting-room');
console.log('Routing checks passed: locale validation, nested paths, query/hash preservation and milestone navigation scope.');
